### ISSUE TITLE
Same scope as pkg2appimage?

### ISSUE THREAD

**Issue by probonopd** [simoniz0r/deb2appimage#8]
Does it have the same scope as https://github.com/AppImage/pkg2appimage? Is there a need for two such tools?

**Comment by simoniz0r** [comment]
If I recall correctly, `pkg2appimage` requires the user to be on a Debian based distro and adds repositories to the user's repository list in order to download packages.  `deb2appimage` works on any distro and downloads the deb packages from either Debian or Ubuntu's repositories using `curl`.

I found adding repositories to be entirely unacceptable and the requiement to be on a Debian based distro completely unnecessary as deb packages are just fancy archives that can just be extracted to the AppDir of the AppImage.

**Comment by probonopd** [comment]
How do you resolve dependencies of those debs?
pkg2appimage doesn't add the repos to the system to do this (it works on a private directory), but it does currently use the system's apt-get.

**Comment by simoniz0r** [comment]
I don't.  That's up to the person packaging it as it should be.

**Comment by probonopd** [comment]
With the almost guaranteed result that the resulting AppImages will run on exactly one machine, the developer's...

**Comment by probonopd** [comment]
I think the proper solution would be to get apt-get bundled, so that deb2appimage does not need to run on a Debian/Ubuntu system.

**Comment by simoniz0r** [comment]
Not at all true.  I test AppImages I build with deb2appimage on ***openSUSE Tumbleweed***.  This is a vastly different system than where the deps are being pulled from.

What exactly is your point here?  Why did you not bring these things up when I submitted deb2appimage?

**Comment by simoniz0r** [comment]
>I think the proper solution would be to get apt-get bundled, so that deb2appimage does not need to run on a Debian/Ubuntu system.

No.  Never.  curl works great.  Extracting the debs works great.  deb2appimage works much nicer than pkg2appimage.

**Comment by simoniz0r** [comment]
If you want to bundle apt-get in pkg2appimage, be my guest.  I will not be doing that.  There is absolutely no reason to do so.  If you want to read the deps from the debs, they are stored in plain text that could very easily be parsed without apt-get (which would also require dpkg and all of its deps).

I personally don't find that to be necessary.  Debian and Ubuntu list the deps on their websites in a nice format that is very easy to read.  Users have had very little trouble asembling AppImages with deb2appimage.

**Comment by simoniz0r** [comment]
I feel like you haven't even read my documentation...

`Build AppImages from deb packages on any distro with simple json configuration`

**Comment by probonopd** [comment]
Simple... I find yaml simple, but I guess it's a matter of preference.
I challenge you to produce a _complete_ AppImage of Visual Studio Code in less lines of code:

```
app: VSCode

ingredients:
  package: code
  dist: trusty
  sources: 
    - deb http://archive.ubuntu.com/ubuntu/ trusty main universe
  script:
    - wget -c --trust-server-names "https://vscode-update.azurewebsites.net/latest/linux-deb-x64/stable"
    - ls code_*.deb | cut -d _ -f 2 > VERSION

script:
  - cp usr/share/applications/code.desktop .
  - cp usr/share/pixmaps/code.png .
  - convert code.png -resize 512x512 usr/share/icons/hicolor/512x512/apps/code.png
```
